### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Perazok** [satisfactorymodding/SatisfactoryModLauncher#13]
I can't choose Early Access or the Experimental version. Also, mods are not displayed, and I can't add a new config. I think Mod Launcher can't find my game folder (C:\Games\SatisfactoryEarlyAccess). I reinstall the game and the launcher, but it didn't help.

In the first version of the Launcher, I could choose the version of the game and install mods, but the game did not start when at list one mod is installed. I'm not sure if this is the same issue.

https://i.imgur.com/lakaJq1.png

**Comment by mircearoata** [comment]
Press view -> enable developer tools, then go to the console tab and send a screenshot of that

**Comment by Perazok** [comment]
This is my screenshot of the console if I did everything right.

https://i.imgur.com/miSeNhB.png

**Comment by mircearoata** [comment]
Did you move the game to an external HDD or moved it somewhere else or something like that?

**Comment by Perazok** [comment]
I reinstalled the game, but the game and launcher are on the same HDD. Right now the game is here: C:\Games\SatisfactoryEarlyAccess and Satisfactory Mod Launcher.exe is here: C:\Users\Gleb\AppData\Local\Programs\satisfactory-mod-launcher-gui

This is my main HDD. I moved some things while I tried to fix this issue, but right now, I have freshly reinstalled Game and Launcher. I didn't do anything with them after reinstallation.

**Comment by mircearoata** [comment]
Released yet another fix for this issue in v1.0.4. Check it out and see if this issue still happens.

**Comment by Perazok** [comment]
Everything works perfectly! The game started, and mods are working. I hope there won't be any more issues. Thank you for this project, and good luck.

**Comment by frehage** [comment]
I have the same issue with a similar error message in the console (see attached [SML_error.log](https://github.com/satisfactorymodding/SatisfactoryModLauncher/files/4774300/SML_error.log)). I am running the new steam version of the game so it is located in the C:\Program Files (x86)\Steam\steamapps\common\Satisfactory

If the issue is that it cannot find the game folder, is there a config available to set the game folder manually?

[SML_error.log](https://github.com/satisfactorymodding/SatisfactoryModLauncher/files/4774300/SML_error.log)
