### ISSUE TITLE
It doesn't work? No readme or how to use.

### ISSUE THREAD

**Issue by Xithyl515** [satisfactorymodding/SatisfactoryModLauncher#3]
https://i.imgur.com/2Lc8WhX.png

This image just shows what's going on. It finds my game and I can remote launch, but there's no button to install SML, and further I can't install any mod on the list because of some SML related error.

**Comment by Ig3l** [comment]
Same here

**Comment by techmasterb** [comment]
yep, same
Error: No version found for dependency SML of 5HbqYVc32UhXNE. All changes were discarded

**Comment by Panakotta00** [comment]
Guys... just... read the discord FAQ...
Nearly no mod is supported and it installs the SML version as you install a mod.

**Comment by Xithyl515** [comment]
Soooo you're saying that this is currently worthless? Also. It would be nice if said FAQ or even discord channel was linked somewhere in the readme.

**Comment by mircearoata** [comment]
Updated to display which mods are updated and which are outdated
There are no mods that worked on Update 3 before, as there was no SML version for Update 3 before today.
You can not download older mods, or if you do, the game won't start because they're incompatible.
There are 4 mods updated now, and all you can do is wait for the others to be updated, it has nothing to do with SMLauncher

**Comment by DiddelmausFX** [comment]
Leute bedankt euch doch erstmal das der Autor eine neue SML herausgebracht hat und die arbeit dahinter, die anderen Autoren werden die Mods sicherlich noch aktualisieren.

Also ich bedanke mich für das zeitgleiche erscheinen der SML - DANKE für deine Arbeit

**Comment by mircearoata** [comment]
As more mods are being updated to work with SML 2.0 and thus SMLauncher (21 Update 3 comatible mods at the moment), and as most of the issues should be fixed now, I will close this issue
