### ISSUE TITLE
Unable to reinstal the mod loader from Mod Launcher

### ISSUE THREAD

**Issue by Michel-Rotta** [satisfactorymodding/SatisfactoryModLauncher#39]
Since the Satifactory update 121119 2020-05-04. I can't start the experimental version of the game.

I suppose it's a mod problem, so I try so remove all the mod, it's don't work any more. I remove the mod launcher from the directory. The game start, without any mod. 

But I can't reinstall the SML from the  Mod Launcher. It thinks the SML is still installed. 

How can I make a force reinstall of the SML 

I think it can be a good idea to add an option to force the reinstallation.

**Comment by mircearoata** [comment]
Instead of removing mods, you should have switched to vanilla config, you probably still have a mod installed. Switch to vanilla and back to modded so that it will install what it thinks you currently have installed. Or switch to vanilla and not back to modded since the experimental update broke SML

**Comment by Michel-Rotta** [comment]
OK, With the passage from Vanilla I have reinstalled the SML 2.1.0

But I can start the game in experimental. I think it's a problem with SML 2.1.0 and the experimental 121119. I'll go tu the SML Issues for that.

I think it can be a good idea to add an option to reinstall the SML on a Factory game. It's seem more easy. 

Many thanks. Be safe.
